### ISSUE TITLE
Copy constructor fails

### ISSUE THREAD

**Issue by jean-m-cyr** [hunter-packages/cpp-netlib#1]
Using head code

```
network::uri u("http://google.com");
cerr << u.host() << '\n';
u = network::uri("http://microsoft.com");
cerr << u.host() << '\n';
```

yields:

```
google.com
microsoft.

```

**Comment by ruslo** [comment]
@jean-m-cyr This fork is for adopting CMake code for Hunter usage. Please report other bugs to upstream: https://github.com/cpp-netlib/cpp-netlib

**Comment by jean-m-cyr** [comment]
@ruslo This fork is several years old and contains bugs that have long since been corrected https://github.com/cpp-netlib/cpp-netlib. Regrettably, the hunter based project build I'm working uses this fork.

**Comment by ruslo** [comment]
@jean-m-cyr Solution is to update this fork, there is `hunter-0.12.0` branch already, feel free to send patches.

**Comment by jean-m-cyr** [comment]
Beyond my skill level.
